### ISSUE TITLE
Comparison with similar projects

### ISSUE THREAD

**Issue by elgalu** [h2oai/h2o-kubeflow#12]
Hi, would it be possible to have a summary of the main differences between this project and similar ones? I've complied a list:

* https://github.com/SeldonIO/seldon-core
* https://github.com/IBM/FfDL
* https://github.com/polyaxon/polyaxon
* https://github.com/PipelineAI/pipeline
* https://github.com/riseml/riseml
* https://github.com/vespa-engine/vespa

Sorry for opening this here, I can also open it [in your Jira project](https://0xdata.atlassian.net/projects/PUBDEV/issues) if you prefer.

**Comment by jlewi** [comment]
Kubeflow is a platform for ML on Kubernetes. We want to make it easy to run a variety of packages on Kubnernets.

See www.kubeflow.org

**Comment by nkpng2k** [comment]
closing this as stale
