### ISSUE TITLE
unable to pull prototype : core 

### ISSUE THREAD

**Issue by sibinnediyoram** [h2oai/h2o-kubeflow#16]
Hi,

 when I tried to configure ks,kubeflow and h2o got stuck in between due to below error,
$ks generate core kubeflow-core --name=kubeflow-core --namespace=kubeflow-test
ERROR no prototype names matched 'core'

I did not find any prototype : core, at all
[root@k8smastr-vanaraj sibin-ml]# ks prototype list
NAME                                     DESCRIPTION
====                                     ===========
io.ksonnet.pkg.ambassador                Ambassador
io.ksonnet.pkg.centraldashboard          centraldashboard
io.ksonnet.pkg.cert-manager              Certificate generation on GKE.
io.ksonnet.pkg.cloud-endpoints           Cloud Endpoint domain creation.
io.ksonnet.pkg.configMap                 A simple config map with optional user-specified data
io.ksonnet.pkg.deployed-service          A deployment exposed with a service
io.ksonnet.pkg.echo-server               A simple echo server.
io.ksonnet.pkg.google-cloud-filestore-pv Creates PV and PVC based on Google Cloud Filestore NFS
io.ksonnet.pkg.h2o3-static               H2O3 Static Cluster
io.ksonnet.pkg.iap-ingress               Ingress for IAP on GKE.
io.ksonnet.pkg.jupyterhub                jupyterhub Component
io.ksonnet.pkg.metric-collector          Service monitor for kubeflow on GCP.
io.ksonnet.pkg.namespace                 Namespace with labels automatically populated from the name
io.ksonnet.pkg.prometheus                Prometheus Service.
io.ksonnet.pkg.single-port-deployment    Replicates a container n times, exposes a single port
io.ksonnet.pkg.single-port-service       Service that exposes a single port
io.ksonnet.pkg.spartakus                 spartakus component for usage collection
io.ksonnet.pkg.tensorboard               ksonnet components for Tensorboard
io.ksonnet.pkg.tf-job-operator           A TensorFlow job operator.
io.ksonnet.pkg.tf-serving                A TensorFlow serving deployment

**Comment by nkpng2k** [comment]
@sibinnediyoram 
Will look into this, but I would encourage you to raise this here:
https://github.com/kubeflow/kubeflow/issues

Looks like an issue with core Kubeflow rather than H2O

**Comment by nkpng2k** [comment]
closing this as stale
