### ISSUE TITLE
Is it not possible to run multiple kubeflow-h2o apps in kubernetes cluster ?

### ISSUE THREAD

**Issue by sibinnediyoram** [h2oai/h2o-kubeflow#17]
Hi,

 I tried to deploy multiple kubeflow + h2o apps in k8s cluster . But it was not properly working out and I noticed that the containers of h2o3-static of first app got replaced with the second one ,even though I created them in a new namespace. Got confused with this and can I get some helps?

**Comment by nkpng2k** [comment]
@sibinnediyoram would you mind sharing the commands run please?

**Comment by nkpng2k** [comment]
I suspect you will either need to use a different deployment name or make a component with a different name:
`ks prototype use io.ksonnet.pkg.h2o3-static <component name> --name <deployment name>`

**Comment by nkpng2k** [comment]
closing this as stale
