### ISSUE TITLE
Documentation Update:

### ISSUE THREAD

**Issue by fjudith** [h2oai/h2o-kubeflow#18]
Hello,

The README.md use the master branch of [kubeflow](https://github.com/kubeflow/kubeflow). There as per v0.2.0 change, the following command is not required anymore as tf-hub have been merged to `kubeflow/core`.

```bash
ks pkg install kubeflow/tf-job
```

Using kubeflow v0.1.x requires the following commands

```bash
KUBEFLOW_VERSION=v0.1.3
KUBEFLOW_REGISTRY="github.com/kubeflow/kubeflow/tree/${KUBEFLOW_VERSION}/kubeflow"

ks pkg install kubeflow/core@${KUBEFLOW_VERSION}
ks pkg install kubeflow/tf-serving@${KUBEFLOW_VERSION}
ks pkg install kubeflow/tf-job@${KUBEFLOW_VERSION}
```

**Comment by smsouthard** [comment]
You have to change the variable KF_VERSION=v0.1.3 to KUBEFLOW_VERSION=v0.1.3 but otherwise this worked well, thanks!

**Comment by nkpng2k** [comment]
I've update the readme documentation associated to this repo. And offloaded configuration of kubeflow documentation --> redirects users to actual kubeflow documentation.
