### ISSUE TITLE
Startup/flatfile generation is broken with the latest kubectl

### ISSUE THREAD

**Issue by AndriiNeverov** [h2oai/h2o-kubeflow#21]
In kubectl 1.13.1, "kubectl get pods -o wide" returns two extra columns "NOMINATED NODE" and "READINESS GATES" both of which may contain "<none>". This breaks docker-startup.sh in a way that it never starts:

if $(kubectl get pods -o wide | grep -q "<none>")
then
    sleep 5

It should also include "grep $DEP_NAME" to focus on h2o pods only.

Another issue related to filtering is that the flatfile may catch any old pods stuck in the "Terminated" state due to the second filter not being specific enough. It should include something like "grep Running".

**Comment by nkpng2k** [comment]
adding fix for this, in branch npng-maintenance

**Comment by nkpng2k** [comment]
should be resolved with this pr: https://github.com/h2oai/h2o-kubeflow/pull/22
